_ -> (`#.*` / `\s+`)*
expr ->
    [
        #ZeroExpressions Delimiter Terminator
        '{' none none '{' '}'

        #ZeroExpressions NoDelimiter Terminator
        '[' none none '[' ']'

        #ZeroExpressions Delimiter NoTerminator
        '?' none none '?'

        #ZeroExpressions NoDelimiter NoTerminator
        '|' none none '|'

        #ZeroExpressions SameDelimiter SameTerminator
        '&' none none '&' '*'

        'identifier' none none `[_a-zA-Z]\w*`
    ]
