expr ->
    [
        'pre_a0'     none 0    'pre_a0'
        '0post_a'    0    none '0post_a'
        '0in_a0'     0    0    '0in_a0'

        'pre_a1'     none 1    'pre_a1'
        '1post_a'    1    none '1post_a'
        '1in_a1'     1    1    '1in_a1'

        'pre_b0'     none 0    'pre_b0'
        '0post_b'    0    none '0post_b'
        '0in_b0'     0    0    '0in_b0'

        'pre_b1'     none 1    'pre_b1'
        '1post_b'    1    none '1post_b'
        '1in_b1'     1    1    '1in_b1'

        'identifier' none none `[_a-zA-Z]\w*`
    ]
