namespace HeartScript.Ast
{
    public enum AstType
    {
        Default,
        UnaryPlus,
        Negate,
        Not,
        Constant,
        MemberAccess,
        Call,
        PostIncrement,
        PostDecrement,
        Multiply,
        Divide,
        Add,
        Subtract,
        LessThanOrEqual,
        GreaterThanOrEqual,
        LessThan,
        GreaterThan,
        Equal,
        NotEqual,
        And,
        ExclusiveOr,
        Or,
        Assign,
        Conditional,
        Convert,
        Parameter,
        Variable,
    }
}
